name: lara_ai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.1.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  sqflite: ^2.2.8+4
  path: ^1.8.3
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^6.1.0
  intl: ^0.20.2
  flutter_localization: ^0.3.3
  lucide_icons: ^0.257.0
  flutter_screenutil: ^5.9.3
  flutter_modular: ^6.4.1

  flutter_localizations:
    sdk: flutter
  local_auth: ^2.3.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  gpt_markdown: ^1.1.5
  mocktail: ^1.0.4
  mockito: ^5.6.3
  bloc_test: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/fonts/roboto/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
